name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java
      run: javac Calculator.java

    - name: Create JAR
      run: jar cfm calculator.jar MANIFEST.MF Calculator.class

    - name: Run tests
      run: java -jar calculator.jar

    - name: Archive JAR
      uses: actions/upload-artifact@v3
      with:
        name: calculator-jar
        path: calculator.jar