name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java files
      run: javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-all-1.3.jar:lib/nanohttpd-2.3.1.jar" -d bin src/Calculator.java tests/CalculatorTest.java

    - name: Run JUnit tests
      run: java -cp "lib/junit-4.13.2.jar:lib/hamcrest-all-1.3.jar:lib/nanohttpd-2.3.1.jar:bin" org.junit.runner.JUnitCore CalculatorTest

    - name: Create JAR
      run: jar cfm calculator.jar MANIFEST.MF bin/Calculator.class

    - name: Archive JAR
      uses: actions/upload-artifact@v4
      with:
        name: calculator-jar
        path: calculator.jar
        